# Generated by Django 6.0.4 on 2026-04-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_submitter_name_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
