# Generated by Django 6.0.4 on 2026-04-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_label_property_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
