# Generated by Django 6.0.4 on 2026-04-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_options_property_price_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='details',
            field=models.JSONField(blank=True, help_text='Flexible JSON bag of type-specific fields (bedrooms, area, furnishing, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='main_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('land', 'Land')], db_index=True, help_text='Top-level category: residential / commercial / land', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sub_type',
            field=models.CharField(blank=True, db_index=True, help_text='Subtype: apartment, villa, house, office, shop, building', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('house', 'House'), ('land', 'Land'), ('commercial', 'Commercial'), ('penthouse', 'Penthouse'), ('other', 'Other'), ('residential', 'Residential'), ('office', 'Office'), ('shop', 'Shop'), ('building', 'Building')], default='apartment', max_length=50),
        ),
    ]
