# Generated by Django 6.0.4 on 2026-05-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_add_main_type_sub_type_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='placements',
            field=models.JSONField(blank=True, default=list, help_text='Page slugs this property is tagged for: buy, rent, commercial, pre_launch, builder_projects'),
        ),
    ]
